swagger: '2.0'
info:
  version: '1.0'
  title: Approval group controller
  contact: {}
host: 132.145.228.83
basePath: /lending-origination/approval-group
securityDefinitions: {}
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /AnRkr/all:
    get:
      summary: get all
      tags:
      - Misc
      operationId: getall
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            default: ''
            items:
              $ref: '#/definitions/getall'
          examples:
            application/json;charset=UTF-8:
            - id: 29888
              syncTs: 2021-11-11T13:28:04.380+0000
              version: 0
              tenantId: AnRkr
              approvalCategoryId: null
              code: AAAA
              name: test
              description: test
              minimumApprovals: 10
              status: ACTIVE
              createdUser: yehan
              createdDate: 2021-11-11T13:28:04.380+0000
              modifiedUser: null
              modifiedDate: null
          headers:
            Date:
              type: string
              default: Thu, 11 Nov 2021 13:31:36 GMT
            Content-Length:
              type: string
              default: '307'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0399bb8503ea74cbf2f3469094e209653"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '130'
  /AnRkr/29888:
    get:
      summary: get by id
      tags:
      - Misc
      operationId: getbyid
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/getbyid'
          examples:
            application/json;charset=UTF-8:
              id: 29888
              syncTs: 2021-11-11T13:28:04.380+0000
              version: 0
              tenantId: AnRkr
              approvalCategoryId: null
              code: AAAA
              name: test
              description: test
              minimumApprovals: 10
              status: ACTIVE
              createdUser: yehan
              createdDate: 2021-11-11T13:28:04.380+0000
              modifiedUser: null
              modifiedDate: null
          headers:
            Date:
              type: string
              default: Thu, 11 Nov 2021 13:31:25 GMT
            Content-Length:
              type: string
              default: '305'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0fdef11b9ee3d17519420b972aec917fe"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '17'
    put:
      summary: update
      tags:
      - Misc
      operationId: update
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters:
      - name: username
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/updaterequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/update'
          examples:
            application/json;charset=UTF-8:
              messages: OK.
              value: '29888'
          headers:
            Date:
              type: string
              default: Fri, 19 Nov 2021 04:27:47 GMT
            Content-Length:
              type: string
              default: '34'
            Connection:
              type: string
              default: keep-alive
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '272'
  /AnRkr/code/AAAA:
    get:
      summary: get by code
      tags:
      - Misc
      operationId: getbycode
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/getbycode'
          examples:
            application/json;charset=UTF-8:
              id: 29888
              syncTs: 2021-11-11T13:28:04.380+0000
              version: 0
              tenantId: AnRkr
              approvalCategoryId: null
              code: AAAA
              name: test
              description: test
              minimumApprovals: 10
              status: ACTIVE
              createdUser: yehan
              createdDate: 2021-11-11T13:28:04.380+0000
              modifiedUser: null
              modifiedDate: null
          headers:
            Date:
              type: string
              default: Thu, 11 Nov 2021 13:44:26 GMT
            Content-Length:
              type: string
              default: '305'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0fdef11b9ee3d17519420b972aec917fe"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '49'
  /AnRkr/name/test:
    get:
      summary: get by name
      tags:
      - Misc
      operationId: getbyname
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            default: ''
            items:
              $ref: '#/definitions/getbyname'
          examples:
            application/json;charset=UTF-8:
            - id: 29888
              syncTs: 2021-11-11T13:28:04.380+0000
              version: 0
              tenantId: AnRkr
              approvalCategoryId: null
              code: AAAA
              name: test
              description: test
              minimumApprovals: 10
              status: ACTIVE
              createdUser: yehan
              createdDate: 2021-11-11T13:28:04.380+0000
              modifiedUser: null
              modifiedDate: null
          headers:
            Date:
              type: string
              default: Thu, 11 Nov 2021 13:45:24 GMT
            Content-Length:
              type: string
              default: '307'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0399bb8503ea74cbf2f3469094e209653"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '15'
  /AnRkr/status/ACTIVE:
    get:
      summary: get by status
      tags:
      - Misc
      operationId: getbystatus
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            default: ''
            items:
              $ref: '#/definitions/getbystatus'
          examples:
            application/json;charset=UTF-8:
            - id: 29888
              syncTs: 2021-11-11T13:28:04.380+0000
              version: 0
              tenantId: AnRkr
              approvalCategoryId: null
              code: AAAA
              name: test
              description: test
              minimumApprovals: 10
              status: ACTIVE
              createdUser: yehan
              createdDate: 2021-11-11T13:28:04.380+0000
              modifiedUser: null
              modifiedDate: null
          headers:
            Date:
              type: string
              default: Thu, 11 Nov 2021 13:46:11 GMT
            Content-Length:
              type: string
              default: '307'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0399bb8503ea74cbf2f3469094e209653"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '15'
  /AnRkr:
    post:
      summary: add
      tags:
      - Misc
      operationId: add
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters:
      - name: username
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/addrequest'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/add'
          examples:
            application/json;charset=UTF-8:
              messages: CREATED.
              value: '29888'
          headers:
            Date:
              type: string
              default: Thu, 11 Nov 2021 13:28:04 GMT
            Content-Length:
              type: string
              default: '39'
            Connection:
              type: string
              default: keep-alive
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '356'
definitions:
  getall:
    title: getall
    example:
      id: 29888
      syncTs: 2021-11-11T13:28:04.380+0000
      version: 0
      tenantId: AnRkr
      approvalCategoryId: null
      code: AAAA
      name: test
      description: test
      minimumApprovals: 10
      status: ACTIVE
      createdUser: yehan
      createdDate: 2021-11-11T13:28:04.380+0000
      modifiedUser: null
      modifiedDate: null
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      approvalCategoryId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      minimumApprovals:
        type: integer
        format: int32
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
    required:
    - id
    - syncTs
    - version
    - tenantId
    - approvalCategoryId
    - code
    - name
    - description
    - minimumApprovals
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
  getall1:
    title: getall1
    example:
      id: 1330450
      syncTs: 2023-02-22T08:23:13.107+0000
      version: 0
      tenantId: AnRkr
      code: TRW1
      name: CATE 123
      description: test
      minimumApprovals: 6
      status: ACTIVE
      createdUser: thiloshana.gamage
      createdDate: 2023-02-22T08:23:13.107+0000
      modifiedUser: null
      modifiedDate: null
      approvalGroupVariableList: null
      approvalGroupPreConditionsList: null
      approvalCategoryDetailsId: 298999
      approvalCategoryDetailsCode: QWEQ
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      minimumApprovals:
        type: integer
        format: int32
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
      approvalGroupVariableList:
        type: string
      approvalGroupPreConditionsList:
        type: string
      approvalCategoryDetailsId:
        type: integer
        format: int32
      approvalCategoryDetailsCode:
        type: string
    required:
    - id
    - syncTs
    - version
    - tenantId
    - code
    - name
    - description
    - minimumApprovals
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
    - approvalGroupVariableList
    - approvalGroupPreConditionsList
    - approvalCategoryDetailsId
    - approvalCategoryDetailsCode
  getbyid:
    title: getbyid
    example:
      id: 29888
      syncTs: 2021-11-11T13:28:04.380+0000
      version: 0
      tenantId: AnRkr
      approvalCategoryId: null
      code: AAAA
      name: test
      description: test
      minimumApprovals: 10
      status: ACTIVE
      createdUser: yehan
      createdDate: 2021-11-11T13:28:04.380+0000
      modifiedUser: null
      modifiedDate: null
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      approvalCategoryId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      minimumApprovals:
        type: integer
        format: int32
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
    required:
    - id
    - syncTs
    - version
    - tenantId
    - approvalCategoryId
    - code
    - name
    - description
    - minimumApprovals
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
  getbycode:
    title: getbycode
    example:
      id: 29888
      syncTs: 2021-11-11T13:28:04.380+0000
      version: 0
      tenantId: AnRkr
      approvalCategoryId: null
      code: AAAA
      name: test
      description: test
      minimumApprovals: 10
      status: ACTIVE
      createdUser: yehan
      createdDate: 2021-11-11T13:28:04.380+0000
      modifiedUser: null
      modifiedDate: null
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      approvalCategoryId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      minimumApprovals:
        type: integer
        format: int32
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
    required:
    - id
    - syncTs
    - version
    - tenantId
    - approvalCategoryId
    - code
    - name
    - description
    - minimumApprovals
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
  getbyname:
    title: getbyname
    example:
      id: 29888
      syncTs: 2021-11-11T13:28:04.380+0000
      version: 0
      tenantId: AnRkr
      approvalCategoryId: null
      code: AAAA
      name: test
      description: test
      minimumApprovals: 10
      status: ACTIVE
      createdUser: yehan
      createdDate: 2021-11-11T13:28:04.380+0000
      modifiedUser: null
      modifiedDate: null
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      approvalCategoryId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      minimumApprovals:
        type: integer
        format: int32
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
    required:
    - id
    - syncTs
    - version
    - tenantId
    - approvalCategoryId
    - code
    - name
    - description
    - minimumApprovals
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
  getbystatus:
    title: getbystatus
    example:
      id: 29888
      syncTs: 2021-11-11T13:28:04.380+0000
      version: 0
      tenantId: AnRkr
      approvalCategoryId: null
      code: AAAA
      name: test
      description: test
      minimumApprovals: 10
      status: ACTIVE
      createdUser: yehan
      createdDate: 2021-11-11T13:28:04.380+0000
      modifiedUser: null
      modifiedDate: null
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      approvalCategoryId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      minimumApprovals:
        type: integer
        format: int32
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
    required:
    - id
    - syncTs
    - version
    - tenantId
    - approvalCategoryId
    - code
    - name
    - description
    - minimumApprovals
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
  addrequest:
    title: addrequest
    example:
      approvalCategoryId: '23160'
      code: AAAA
      daLimits:
      - fromAmount: '10'
        toAmount: '100'
        variable: ''
      description: test
      minimumApprovalNo: '10'
      name: test
      preConditions:
      - approvalLevelId: '23209'
        group: '1'
        mandatory: YES
        sequence: '1'
        status: ACTIVE
      status: ACTIVE
    type: object
    properties:
      approvalCategoryId:
        type: string
      code:
        type: string
      daLimits:
        type: array
        items:
          $ref: '#/definitions/DaLimit'
      description:
        type: string
      minimumApprovalNo:
        type: string
      name:
        type: string
      preConditions:
        type: array
        items:
          $ref: '#/definitions/PreCondition'
      status:
        type: string
    required:
    - approvalCategoryId
    - code
    - daLimits
    - description
    - minimumApprovalNo
    - name
    - preConditions
    - status
  DaLimit:
    title: DaLimit
    example:
      fromAmount: '10'
      toAmount: '100'
      variable: ''
    type: object
    properties:
      fromAmount:
        type: string
      toAmount:
        type: string
      variable:
        type: string
    required:
    - fromAmount
    - toAmount
    - variable
  PreCondition:
    title: PreCondition
    example:
      approvalLevelId: '23209'
      group: '1'
      mandatory: YES
      sequence: '1'
      status: ACTIVE
    type: object
    properties:
      approvalLevelId:
        type: string
      group:
        type: string
      mandatory:
        type: string
      sequence:
        type: string
      status:
        type: string
    required:
    - approvalLevelId
    - group
    - mandatory
    - sequence
    - status
  add:
    title: add
    example:
      messages: CREATED.
      value: '29888'
    type: object
    properties:
      messages:
        type: string
      value:
        type: string
    required:
    - messages
    - value
  updaterequest:
    title: updaterequest
    example:
      approvalCategoryId: '23160'
      code: AAAA
      daLimits:
      - fromAmount: '10'
        toAmount: '100'
        variable: ''
      description: test
      minimumApprovalNo: '10'
      name: test
      preConditions:
      - approvalLevelId: '23209'
        group: '1'
        mandatory: YES
        sequence: '1'
        status: ACTIVE
      status: ACTIVE
      version: '0'
    type: object
    properties:
      approvalCategoryId:
        type: string
      code:
        type: string
      daLimits:
        type: array
        items:
          $ref: '#/definitions/DaLimit'
      description:
        type: string
      minimumApprovalNo:
        type: string
      name:
        type: string
      preConditions:
        type: array
        items:
          $ref: '#/definitions/PreCondition'
      status:
        type: string
      version:
        type: string
    required:
    - approvalCategoryId
    - code
    - daLimits
    - description
    - minimumApprovalNo
    - name
    - preConditions
    - status
    - version
  update:
    title: update
    example:
      messages: OK.
      value: '29888'
    type: object
    properties:
      messages:
        type: string
      value:
        type: string
    required:
    - messages
    - value
tags:
- name: Misc
  description: ''
