swagger: '2.0'
info:
  version: '1.0'
  title: Transaction Allocation Template controller
  contact: {}
host: 132.145.228.83
basePath: /lending-transaction/allocation-template
securityDefinitions: {}
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /AnRkr/all:
    get:
      summary: Find All
      tags:
      - Misc
      operationId: FindAll
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            default: ''
            items:
              $ref: '#/definitions/FindAll'
          examples:
            application/json;charset=UTF-8:
            - id: 255696
              version: 0
              syncTs: 2022-08-08T09:44:06.162+0000
              tenantId: AnRkr
              code: ABHI
              name: Allocation Template 4
              loanAccountStatusId: 2
              loanAccountStatusCode: ATS2
              loanAccountStatusName: null
              status: INACTIVE
              createdUser: prageeth
              createdDate: 2022-08-08T09:44:06.162+0000
              modifiedUser: null
              modifiedDate: null
            - id: 262675
              version: 0
              syncTs: 2022-08-22T11:30:20.623+0000
              tenantId: AnRkr
              code: TES1
              name: TEST1
              loanAccountStatusId: 169007
              loanAccountStatusCode: INIT
              loanAccountStatusName: Account Initiated
              status: INACTIVE
              createdUser: lahiru
              createdDate: 2022-08-22T11:30:20.623+0000
              modifiedUser: null
              modifiedDate: null
            - id: 262676
              version: 0
              syncTs: 2022-08-22T11:33:42.942+0000
              tenantId: AnRkr
              code: TES2
              name: TEST2
              loanAccountStatusId: 169011
              loanAccountStatusCode: RESH
              loanAccountStatusName: RESCHEDULED
              status: INACTIVE
              createdUser: lahiru
              createdDate: 2022-08-22T11:33:42.942+0000
              modifiedUser: null
              modifiedDate: null
            - id: 1
              version: 2
              syncTs: 2023-06-07T03:50:29.561+0000
              tenantId: AnRkr
              code: TAT5
              name: Allocation Template
              loanAccountStatusId: 314175
              loanAccountStatusCode: INIT
              loanAccountStatusName: INITIATED
              status: ACTIVE
              createdUser: sadeep
              createdDate: 2022-08-26T10:38:36.462+0000
              modifiedUser: sahan.peiris
              modifiedDate: 2023-06-07T03:50:29.561+0000
            - id: 979140
              version: 0
              syncTs: 2023-01-11T06:52:29.469+0000
              tenantId: AnRkr
              code: '1144'
              name: ABCD abcd4
              loanAccountStatusId: 169009
              loanAccountStatusCode: ACTV
              loanAccountStatusName: Account Active
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-01-11T06:52:29.469+0000
              modifiedUser: null
              modifiedDate: null
            - id: 1640509
              version: 0
              syncTs: 2023-04-21T12:45:29.845+0000
              tenantId: AnRkr
              code: AEXP
              name: ACCOUNT EXPIRED
              loanAccountStatusId: 576757
              loanAccountStatusCode: EXPR
              loanAccountStatusName: EXPIRED
              status: INACTIVE
              createdUser: DilanthaM
              createdDate: 2023-04-21T12:45:29.845+0000
              modifiedUser: null
              modifiedDate: null
            - id: 256259
              version: 1
              syncTs: 2022-08-09T10:09:08.312+0000
              tenantId: AnRkr
              code: AAZZ
              name: nameaazz update
              loanAccountStatusId: 169007
              loanAccountStatusCode: INIT
              loanAccountStatusName: null
              status: INACTIVE
              createdUser: ishan
              createdDate: 2022-08-09T10:07:01.692+0000
              modifiedUser: null
              modifiedDate: 2022-08-09T10:09:08.312+0000
            - id: 270693
              version: 0
              syncTs: 2022-08-23T08:27:04.261+0000
              tenantId: AnRkr
              code: TES3
              name: TEST3 edit
              loanAccountStatusId: 169011
              loanAccountStatusCode: RESH
              loanAccountStatusName: RESCHEDULED
              status: INACTIVE
              createdUser: lahiru
              createdDate: 2022-08-23T08:27:04.261+0000
              modifiedUser: null
              modifiedDate: null
            - id: 1843047
              version: 0
              syncTs: 2023-07-05T07:09:48.884+0000
              tenantId: AnRkr
              code: FSAT
              name: Allocation Template2
              loanAccountStatusId: 576757
              loanAccountStatusCode: EXPR
              loanAccountStatusName: EXPIRED
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-07-05T07:09:48.884+0000
              modifiedUser: null
              modifiedDate: null
            - id: 1312326
              version: 1
              syncTs: 2023-02-07T10:48:03.404+0000
              tenantId: AnRkr
              code: 07FB
              name: 07th feb testing by nipuni
              loanAccountStatusId: 959894
              loanAccountStatusCode: JAN0
              loanAccountStatusName: ABCD abcd
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-02-07T10:47:52.972+0000
              modifiedUser: sahan.peiris
              modifiedDate: 2023-02-07T10:48:03.404+0000
            - id: 1663934
              version: 0
              syncTs: 2023-05-09T08:12:45.825+0000
              tenantId: AnRkr
              code: NV01
              name: Test NV01
              loanAccountStatusId: 314165
              loanAccountStatusCode: CRET
              loanAccountStatusName: CREATED
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-05-09T08:12:45.825+0000
              modifiedUser: null
              modifiedDate: null
            - id: 1665513
              version: 3
              syncTs: 2023-05-11T06:49:07.767+0000
              tenantId: AnRkr
              code: NV02
              name: Test Name NV02
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-05-09T17:50:48.425+0000
              modifiedUser: sahan.peiris
              modifiedDate: 2023-05-11T06:49:07.767+0000
            - id: 1742305
              version: 0
              syncTs: 2023-05-30T10:04:26.343+0000
              tenantId: AnRkr
              code: ASA1
              name: Sample QA
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: INACTIVE
              createdUser: acentura.testing
              createdDate: 2023-05-30T10:04:26.343+0000
              modifiedUser: null
              modifiedDate: null
            - id: 258078
              version: 0
              syncTs: 2022-08-13T15:58:03.018+0000
              tenantId: AnRkr
              code: BBBB
              name: B gang
              loanAccountStatusId: 169007
              loanAccountStatusCode: INIT
              loanAccountStatusName: Account Initiated
              status: INACTIVE
              createdUser: ishan
              createdDate: 2022-08-13T15:58:03.018+0000
              modifiedUser: null
              modifiedDate: null
            - id: 272919
              version: 6
              syncTs: 2023-07-05T07:07:50.094+0000
              tenantId: AnRkr
              code: ACH2
              name: Template Name
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: ACTIVE
              createdUser: lahiru
              createdDate: 2022-08-24T07:26:24.905+0000
              modifiedUser: thiloshana.gamage
              modifiedDate: 2023-07-05T07:07:50.094+0000
            - id: 1028189
              version: 1
              syncTs: 2023-05-03T12:02:49.966+0000
              tenantId: AnRkr
              code: TYUI
              name: hhjklllll
              loanAccountStatusId: 500367
              loanAccountStatusCode: HOLD
              loanAccountStatusName: HOLD
              status: INACTIVE
              createdUser: MilanCha
              createdDate: 2023-01-19T11:42:29.625+0000
              modifiedUser: MilanCha
              modifiedDate: 2023-05-03T12:02:49.966+0000
            - id: 1120089
              version: 1
              syncTs: 2023-01-23T04:07:42.623+0000
              tenantId: AnRkr
              code: 23JN
              name: test update fucntion by Nipuni - update
              loanAccountStatusId: 169006
              loanAccountStatusCode: CREA
              loanAccountStatusName: Account Created
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-01-23T04:04:13.668+0000
              modifiedUser: sahan.peiris
              modifiedDate: 2023-01-23T04:07:42.623+0000
            - id: 21
              version: 0
              syncTs: 2023-02-23T13:41:40.218+0000
              tenantId: AnRkr
              code: TAT6
              name: Transaction Allocation Template 6
              loanAccountStatusId: 1
              loanAccountStatusCode: XXXX
              loanAccountStatusName: Account Status
              status: INACTIVE
              createdUser: sadeep
              createdDate: 2023-02-23T13:41:36.137+0000
              modifiedUser: null
              modifiedDate: null
            - id: 252828
              version: 1
              syncTs: 2023-05-15T13:46:21.428+0000
              tenantId: AnRkr
              code: TAT4
              name: Allocation Temp
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: INACTIVE
              createdUser: prageeth
              createdDate: 2022-08-01T06:43:15.710+0000
              modifiedUser: sahan.peiris
              modifiedDate: 2023-05-15T13:46:21.428+0000
            - id: 257753
              version: 1
              syncTs: 2022-08-12T06:12:05.479+0000
              tenantId: AnRkr
              code: AAZb
              name: nameaazz update
              loanAccountStatusId: 169007
              loanAccountStatusCode: INIT
              loanAccountStatusName: Account Initiated
              status: INACTIVE
              createdUser: ishan
              createdDate: 2022-08-12T06:06:55.355+0000
              modifiedUser: null
              modifiedDate: 2022-08-12T06:12:05.479+0000
            - id: 272918
              version: 0
              syncTs: 2022-08-24T07:26:24.905+0000
              tenantId: AnRkr
              code: ABH2
              name: Template Name
              loanAccountStatusId: 169009
              loanAccountStatusCode: ACTV
              loanAccountStatusName: Account Active
              status: INACTIVE
              createdUser: lahiru
              createdDate: 2022-08-24T07:26:24.905+0000
              modifiedUser: null
              modifiedDate: null
            - id: 979112
              version: 2
              syncTs: 2023-01-19T17:20:28.518+0000
              tenantId: AnRkr
              code: 125U
              name: Nipuni Witharanage updated 11
              loanAccountStatusId: 169012
              loanAccountStatusCode: CANC
              loanAccountStatusName: Account Cancelled
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-01-11T06:51:58.961+0000
              modifiedUser: milan
              modifiedDate: 2023-01-19T17:20:28.518+0000
            - id: 1751400
              version: 0
              syncTs: 2023-06-01T05:46:01.162+0000
              tenantId: AnRkr
              code: AXAX
              name: Dev test
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-06-01T05:46:01.162+0000
              modifiedUser: null
              modifiedDate: null
            - id: 1754159
              version: 0
              syncTs: 2023-06-01T10:48:50.708+0000
              tenantId: AnRkr
              code: XCXC
              name: Dev test 2
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: INACTIVE
              createdUser: acentura.testing
              createdDate: 2023-06-01T10:48:50.708+0000
              modifiedUser: null
              modifiedDate: null
          headers:
            Date:
              type: string
              default: Fri, 21 Jul 2023 09:33:22 GMT
            Content-Length:
              type: string
              default: '8773'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0b6069dd0c712583f8ff62d54548c62c0"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '200'
  /AnRkr/code/TAT4:
    get:
      summary: Find By Code
      tags:
      - Misc
      operationId: FindByCode
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/FindByCode'
          examples:
            application/json;charset=UTF-8:
              id: 252828
              version: 1
              syncTs: 2023-05-15T13:46:21.428+0000
              tenantId: AnRkr
              code: TAT4
              name: Allocation Temp
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: INACTIVE
              createdUser: prageeth
              createdDate: 2022-08-01T06:43:15.710+0000
              modifiedUser: sahan.peiris
              modifiedDate: 2023-05-15T13:46:21.428+0000
          headers:
            Date:
              type: string
              default: Fri, 21 Jul 2023 09:33:38 GMT
            Content-Length:
              type: string
              default: '382'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0c821c4a133323bc112180afa58938eb2"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '34'
  /AnRkr/name/name:
    get:
      summary: Find By Name
      tags:
      - Misc
      operationId: FindByName
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            default: ''
            items:
              $ref: '#/definitions/FindByName'
          examples:
            application/json;charset=UTF-8:
            - id: 256259
              version: 1
              syncTs: 2022-08-09T10:09:08.312+0000
              tenantId: AnRkr
              code: AAZZ
              name: nameaazz update
              loanAccountStatusId: 169007
              loanAccountStatusCode: INIT
              loanAccountStatusName: null
              status: INACTIVE
              createdUser: ishan
              createdDate: 2022-08-09T10:07:01.692+0000
              modifiedUser: null
              modifiedDate: 2022-08-09T10:09:08.312+0000
            - id: 257753
              version: 1
              syncTs: 2022-08-12T06:12:05.479+0000
              tenantId: AnRkr
              code: AAZb
              name: nameaazz update
              loanAccountStatusId: 169007
              loanAccountStatusCode: INIT
              loanAccountStatusName: Account Initiated
              status: INACTIVE
              createdUser: ishan
              createdDate: 2022-08-12T06:06:55.355+0000
              modifiedUser: null
              modifiedDate: 2022-08-12T06:12:05.479+0000
          headers:
            Date:
              type: string
              default: Fri, 21 Jul 2023 09:34:37 GMT
            Content-Length:
              type: string
              default: '748'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0890dd7410067b9c9d9690987fd5da71d"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '16'
  /AnRkr/status/INACTIVE:
    get:
      summary: Find By Status
      tags:
      - Misc
      operationId: FindByStatus
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            default: ''
            items:
              $ref: '#/definitions/FindByStatus'
          examples:
            application/json;charset=UTF-8:
            - id: 255696
              version: 0
              syncTs: 2022-08-08T09:44:06.162+0000
              tenantId: AnRkr
              code: ABHI
              name: Allocation Template 4
              loanAccountStatusId: 2
              loanAccountStatusCode: ATS2
              loanAccountStatusName: null
              status: INACTIVE
              createdUser: prageeth
              createdDate: 2022-08-08T09:44:06.162+0000
              modifiedUser: null
              modifiedDate: null
            - id: 262675
              version: 0
              syncTs: 2022-08-22T11:30:20.623+0000
              tenantId: AnRkr
              code: TES1
              name: TEST1
              loanAccountStatusId: 169007
              loanAccountStatusCode: INIT
              loanAccountStatusName: Account Initiated
              status: INACTIVE
              createdUser: lahiru
              createdDate: 2022-08-22T11:30:20.623+0000
              modifiedUser: null
              modifiedDate: null
            - id: 262676
              version: 0
              syncTs: 2022-08-22T11:33:42.942+0000
              tenantId: AnRkr
              code: TES2
              name: TEST2
              loanAccountStatusId: 169011
              loanAccountStatusCode: RESH
              loanAccountStatusName: RESCHEDULED
              status: INACTIVE
              createdUser: lahiru
              createdDate: 2022-08-22T11:33:42.942+0000
              modifiedUser: null
              modifiedDate: null
            - id: 979140
              version: 0
              syncTs: 2023-01-11T06:52:29.469+0000
              tenantId: AnRkr
              code: '1144'
              name: ABCD abcd4
              loanAccountStatusId: 169009
              loanAccountStatusCode: ACTV
              loanAccountStatusName: Account Active
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-01-11T06:52:29.469+0000
              modifiedUser: null
              modifiedDate: null
            - id: 1640509
              version: 0
              syncTs: 2023-04-21T12:45:29.845+0000
              tenantId: AnRkr
              code: AEXP
              name: ACCOUNT EXPIRED
              loanAccountStatusId: 576757
              loanAccountStatusCode: EXPR
              loanAccountStatusName: EXPIRED
              status: INACTIVE
              createdUser: DilanthaM
              createdDate: 2023-04-21T12:45:29.845+0000
              modifiedUser: null
              modifiedDate: null
            - id: 256259
              version: 1
              syncTs: 2022-08-09T10:09:08.312+0000
              tenantId: AnRkr
              code: AAZZ
              name: nameaazz update
              loanAccountStatusId: 169007
              loanAccountStatusCode: INIT
              loanAccountStatusName: null
              status: INACTIVE
              createdUser: ishan
              createdDate: 2022-08-09T10:07:01.692+0000
              modifiedUser: null
              modifiedDate: 2022-08-09T10:09:08.312+0000
            - id: 270693
              version: 0
              syncTs: 2022-08-23T08:27:04.261+0000
              tenantId: AnRkr
              code: TES3
              name: TEST3 edit
              loanAccountStatusId: 169011
              loanAccountStatusCode: RESH
              loanAccountStatusName: RESCHEDULED
              status: INACTIVE
              createdUser: lahiru
              createdDate: 2022-08-23T08:27:04.261+0000
              modifiedUser: null
              modifiedDate: null
            - id: 1312326
              version: 1
              syncTs: 2023-02-07T10:48:03.404+0000
              tenantId: AnRkr
              code: 07FB
              name: 07th feb testing by nipuni
              loanAccountStatusId: 959894
              loanAccountStatusCode: JAN0
              loanAccountStatusName: ABCD abcd
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-02-07T10:47:52.972+0000
              modifiedUser: sahan.peiris
              modifiedDate: 2023-02-07T10:48:03.404+0000
            - id: 1663934
              version: 0
              syncTs: 2023-05-09T08:12:45.825+0000
              tenantId: AnRkr
              code: NV01
              name: Test NV01
              loanAccountStatusId: 314165
              loanAccountStatusCode: CRET
              loanAccountStatusName: CREATED
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-05-09T08:12:45.825+0000
              modifiedUser: null
              modifiedDate: null
            - id: 1665513
              version: 3
              syncTs: 2023-05-11T06:49:07.767+0000
              tenantId: AnRkr
              code: NV02
              name: Test Name NV02
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-05-09T17:50:48.425+0000
              modifiedUser: sahan.peiris
              modifiedDate: 2023-05-11T06:49:07.767+0000
            - id: 1742305
              version: 0
              syncTs: 2023-05-30T10:04:26.343+0000
              tenantId: AnRkr
              code: ASA1
              name: Sample QA
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: INACTIVE
              createdUser: acentura.testing
              createdDate: 2023-05-30T10:04:26.343+0000
              modifiedUser: null
              modifiedDate: null
            - id: 258078
              version: 0
              syncTs: 2022-08-13T15:58:03.018+0000
              tenantId: AnRkr
              code: BBBB
              name: B gang
              loanAccountStatusId: 169007
              loanAccountStatusCode: INIT
              loanAccountStatusName: Account Initiated
              status: INACTIVE
              createdUser: ishan
              createdDate: 2022-08-13T15:58:03.018+0000
              modifiedUser: null
              modifiedDate: null
            - id: 1028189
              version: 1
              syncTs: 2023-05-03T12:02:49.966+0000
              tenantId: AnRkr
              code: TYUI
              name: hhjklllll
              loanAccountStatusId: 500367
              loanAccountStatusCode: HOLD
              loanAccountStatusName: HOLD
              status: INACTIVE
              createdUser: MilanCha
              createdDate: 2023-01-19T11:42:29.625+0000
              modifiedUser: MilanCha
              modifiedDate: 2023-05-03T12:02:49.966+0000
            - id: 1120089
              version: 1
              syncTs: 2023-01-23T04:07:42.623+0000
              tenantId: AnRkr
              code: 23JN
              name: test update fucntion by Nipuni - update
              loanAccountStatusId: 169006
              loanAccountStatusCode: CREA
              loanAccountStatusName: Account Created
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-01-23T04:04:13.668+0000
              modifiedUser: sahan.peiris
              modifiedDate: 2023-01-23T04:07:42.623+0000
            - id: 21
              version: 0
              syncTs: 2023-02-23T13:41:40.218+0000
              tenantId: AnRkr
              code: TAT6
              name: Transaction Allocation Template 6
              loanAccountStatusId: 1
              loanAccountStatusCode: XXXX
              loanAccountStatusName: Account Status
              status: INACTIVE
              createdUser: sadeep
              createdDate: 2023-02-23T13:41:36.137+0000
              modifiedUser: null
              modifiedDate: null
            - id: 252828
              version: 1
              syncTs: 2023-05-15T13:46:21.428+0000
              tenantId: AnRkr
              code: TAT4
              name: Allocation Temp
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: INACTIVE
              createdUser: prageeth
              createdDate: 2022-08-01T06:43:15.710+0000
              modifiedUser: sahan.peiris
              modifiedDate: 2023-05-15T13:46:21.428+0000
            - id: 257753
              version: 1
              syncTs: 2022-08-12T06:12:05.479+0000
              tenantId: AnRkr
              code: AAZb
              name: nameaazz update
              loanAccountStatusId: 169007
              loanAccountStatusCode: INIT
              loanAccountStatusName: Account Initiated
              status: INACTIVE
              createdUser: ishan
              createdDate: 2022-08-12T06:06:55.355+0000
              modifiedUser: null
              modifiedDate: 2022-08-12T06:12:05.479+0000
            - id: 272918
              version: 0
              syncTs: 2022-08-24T07:26:24.905+0000
              tenantId: AnRkr
              code: ABH2
              name: Template Name
              loanAccountStatusId: 169009
              loanAccountStatusCode: ACTV
              loanAccountStatusName: Account Active
              status: INACTIVE
              createdUser: lahiru
              createdDate: 2022-08-24T07:26:24.905+0000
              modifiedUser: null
              modifiedDate: null
            - id: 979112
              version: 2
              syncTs: 2023-01-19T17:20:28.518+0000
              tenantId: AnRkr
              code: 125U
              name: Nipuni Witharanage updated 11
              loanAccountStatusId: 169012
              loanAccountStatusCode: CANC
              loanAccountStatusName: Account Cancelled
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-01-11T06:51:58.961+0000
              modifiedUser: milan
              modifiedDate: 2023-01-19T17:20:28.518+0000
            - id: 1751400
              version: 0
              syncTs: 2023-06-01T05:46:01.162+0000
              tenantId: AnRkr
              code: AXAX
              name: Dev test
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: INACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-06-01T05:46:01.162+0000
              modifiedUser: null
              modifiedDate: null
            - id: 1754159
              version: 0
              syncTs: 2023-06-01T10:48:50.708+0000
              tenantId: AnRkr
              code: XCXC
              name: Dev test 2
              loanAccountStatusId: 341028
              loanAccountStatusCode: ACTV
              loanAccountStatusName: ACTIVE
              status: INACTIVE
              createdUser: acentura.testing
              createdDate: 2023-06-01T10:48:50.708+0000
              modifiedUser: null
              modifiedDate: null
          headers:
            Date:
              type: string
              default: Fri, 21 Jul 2023 09:34:55 GMT
            Content-Length:
              type: string
              default: '7649'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"07b0f99291b548a2888158f3a1dec77b7"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '14'
  /AnRkr/workflow-items/search:
    get:
      summary: Find By Pending Status
      tags:
      - Misc
      operationId: FindByPendingStatus
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters:
      - name: status
        in: query
        required: true
        type: string
        description: ''
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/FindByPendingStatus'
          examples:
            application/json;charset=UTF-8:
              content: []
              pageable:
                sort:
                  sorted: false
                  unsorted: true
                  empty: true
                pageSize: 10
                pageNumber: 0
                offset: 0
                paged: true
                unpaged: false
              totalPages: 0
              totalElements: 0
              last: true
              sort:
                sorted: false
                unsorted: true
                empty: true
              numberOfElements: 0
              first: true
              size: 10
              number: 0
              empty: true
          headers:
            Date:
              type: string
              default: Fri, 21 Jul 2023 09:45:38 GMT
            Content-Length:
              type: string
              default: '315'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0d1c55ce2efdbb315ee93d253d833be93"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '83'
  /AnRkr/pending-id/23194:
    get:
      summary: Find By Pending ID
      tags:
      - Misc
      operationId: FindByPendingID
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        '204':
          description: No Content
          headers:
            Date:
              type: string
              default: Fri, 21 Jul 2023 09:45:54 GMT
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0d6d4b3dff6828a0667c336fa89847960"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '15'
  /AnRkr/123:
    get:
      summary: Get By Id
      tags:
      - Misc
      operationId: GetById
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        '204':
          description: No Content
          headers:
            Date:
              type: string
              default: Fri, 21 Jul 2023 09:46:07 GMT
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0d6d4b3dff6828a0667c336fa89847960"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '10'
  /AnRkr:
    post:
      summary: Create
      tags:
      - Misc
      operationId: Create
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters:
      - name: username
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreateRequest'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/Create'
          examples:
            application/json;charset=UTF-8:
              messages: CREATED.
              value: '1895623'
          headers:
            Date:
              type: string
              default: Fri, 21 Jul 2023 10:53:17 GMT
            Content-Length:
              type: string
              default: '41'
            Connection:
              type: string
              default: keep-alive
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '189'
  /AnRkr/23198:
    put:
      summary: Update
      tags:
      - Misc
      operationId: Update
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters:
      - name: username
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/UpdateRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Update'
          examples:
            application/json;charset=UTF-8:
              messages: OK.
              value: '1895623'
          headers:
            Date:
              type: string
              default: Fri, 21 Jul 2023 11:10:41 GMT
            Content-Length:
              type: string
              default: '36'
            Connection:
              type: string
              default: keep-alive
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '202'
definitions:
  FindAll:
    title: FindAll
    example:
      id: 255696
      version: 0
      syncTs: 2022-08-08T09:44:06.162+0000
      tenantId: AnRkr
      code: ABHI
      name: Allocation Template 4
      loanAccountStatusId: 2
      loanAccountStatusCode: ATS2
      loanAccountStatusName: null
      status: INACTIVE
      createdUser: prageeth
      createdDate: 2022-08-08T09:44:06.162+0000
      modifiedUser: null
      modifiedDate: null
    type: object
    properties:
      id:
        type: integer
        format: int32
      version:
        type: integer
        format: int32
      syncTs:
        type: string
      tenantId:
        type: string
      code:
        type: string
      name:
        type: string
      loanAccountStatusId:
        type: integer
        format: int32
      loanAccountStatusCode:
        type: string
      loanAccountStatusName:
        type: string
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
    required:
    - id
    - version
    - syncTs
    - tenantId
    - code
    - name
    - loanAccountStatusId
    - loanAccountStatusCode
    - loanAccountStatusName
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
  FindByCode:
    title: FindByCode
    example:
      id: 252828
      version: 1
      syncTs: 2023-05-15T13:46:21.428+0000
      tenantId: AnRkr
      code: TAT4
      name: Allocation Temp
      loanAccountStatusId: 341028
      loanAccountStatusCode: ACTV
      loanAccountStatusName: ACTIVE
      status: INACTIVE
      createdUser: prageeth
      createdDate: 2022-08-01T06:43:15.710+0000
      modifiedUser: sahan.peiris
      modifiedDate: 2023-05-15T13:46:21.428+0000
    type: object
    properties:
      id:
        type: integer
        format: int32
      version:
        type: integer
        format: int32
      syncTs:
        type: string
      tenantId:
        type: string
      code:
        type: string
      name:
        type: string
      loanAccountStatusId:
        type: integer
        format: int32
      loanAccountStatusCode:
        type: string
      loanAccountStatusName:
        type: string
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
    required:
    - id
    - version
    - syncTs
    - tenantId
    - code
    - name
    - loanAccountStatusId
    - loanAccountStatusCode
    - loanAccountStatusName
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
  FindByName:
    title: FindByName
    example:
      id: 256259
      version: 1
      syncTs: 2022-08-09T10:09:08.312+0000
      tenantId: AnRkr
      code: AAZZ
      name: nameaazz update
      loanAccountStatusId: 169007
      loanAccountStatusCode: INIT
      loanAccountStatusName: null
      status: INACTIVE
      createdUser: ishan
      createdDate: 2022-08-09T10:07:01.692+0000
      modifiedUser: null
      modifiedDate: 2022-08-09T10:09:08.312+0000
    type: object
    properties:
      id:
        type: integer
        format: int32
      version:
        type: integer
        format: int32
      syncTs:
        type: string
      tenantId:
        type: string
      code:
        type: string
      name:
        type: string
      loanAccountStatusId:
        type: integer
        format: int32
      loanAccountStatusCode:
        type: string
      loanAccountStatusName:
        type: string
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
    required:
    - id
    - version
    - syncTs
    - tenantId
    - code
    - name
    - loanAccountStatusId
    - loanAccountStatusCode
    - loanAccountStatusName
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
  FindByStatus:
    title: FindByStatus
    example:
      id: 255696
      version: 0
      syncTs: 2022-08-08T09:44:06.162+0000
      tenantId: AnRkr
      code: ABHI
      name: Allocation Template 4
      loanAccountStatusId: 2
      loanAccountStatusCode: ATS2
      loanAccountStatusName: null
      status: INACTIVE
      createdUser: prageeth
      createdDate: 2022-08-08T09:44:06.162+0000
      modifiedUser: null
      modifiedDate: null
    type: object
    properties:
      id:
        type: integer
        format: int32
      version:
        type: integer
        format: int32
      syncTs:
        type: string
      tenantId:
        type: string
      code:
        type: string
      name:
        type: string
      loanAccountStatusId:
        type: integer
        format: int32
      loanAccountStatusCode:
        type: string
      loanAccountStatusName:
        type: string
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
    required:
    - id
    - version
    - syncTs
    - tenantId
    - code
    - name
    - loanAccountStatusId
    - loanAccountStatusCode
    - loanAccountStatusName
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
  FindByPendingStatus:
    title: FindByPendingStatus
    example:
      content: []
      pageable:
        sort:
          sorted: false
          unsorted: true
          empty: true
        pageSize: 10
        pageNumber: 0
        offset: 0
        paged: true
        unpaged: false
      totalPages: 0
      totalElements: 0
      last: true
      sort:
        sorted: false
        unsorted: true
        empty: true
      numberOfElements: 0
      first: true
      size: 10
      number: 0
      empty: true
    type: object
    properties:
      content:
        type: array
        items:
          type: string
      pageable:
        $ref: '#/definitions/Pageable'
      totalPages:
        type: integer
        format: int32
      totalElements:
        type: integer
        format: int32
      last:
        type: boolean
      sort:
        $ref: '#/definitions/Sort'
      numberOfElements:
        type: integer
        format: int32
      first:
        type: boolean
      size:
        type: integer
        format: int32
      number:
        type: integer
        format: int32
      empty:
        type: boolean
    required:
    - content
    - pageable
    - totalPages
    - totalElements
    - last
    - sort
    - numberOfElements
    - first
    - size
    - number
    - empty
  Pageable:
    title: Pageable
    example:
      sort:
        sorted: false
        unsorted: true
        empty: true
      pageSize: 10
      pageNumber: 0
      offset: 0
      paged: true
      unpaged: false
    type: object
    properties:
      sort:
        $ref: '#/definitions/Sort'
      pageSize:
        type: integer
        format: int32
      pageNumber:
        type: integer
        format: int32
      offset:
        type: integer
        format: int32
      paged:
        type: boolean
      unpaged:
        type: boolean
    required:
    - sort
    - pageSize
    - pageNumber
    - offset
    - paged
    - unpaged
  Sort:
    title: Sort
    example:
      sorted: false
      unsorted: true
      empty: true
    type: object
    properties:
      sorted:
        type: boolean
      unsorted:
        type: boolean
      empty:
        type: boolean
    required:
    - sorted
    - unsorted
    - empty
  CreateRequest:
    title: CreateRequest
    example:
      accountStatusId: '2'
      accountStatusName: Status 2
      code: TAT4
      name: Allocation Template 4
      status: ACTIVE
    type: object
    properties:
      accountStatusId:
        type: string
      accountStatusName:
        type: string
      code:
        type: string
      name:
        type: string
      status:
        type: string
    required:
    - accountStatusId
    - accountStatusName
    - code
    - name
    - status
  Create:
    title: Create
    example:
      messages: CREATED.
      value: '1895623'
    type: object
    properties:
      messages:
        type: string
      value:
        type: string
    required:
    - messages
    - value
  UpdateRequest:
    title: UpdateRequest
    example:
      accountStatusId: '1'
      accountStatusName: account status
      code: TAT4
      name: Allocation Template Update 3
      status: ACTIVE
      version: '0'
    type: object
    properties:
      accountStatusId:
        type: string
      accountStatusName:
        type: string
      code:
        type: string
      name:
        type: string
      status:
        type: string
      version:
        type: string
    required:
    - accountStatusId
    - accountStatusName
    - code
    - name
    - status
    - version
  Update:
    title: Update
    example:
      messages: OK.
      value: '1895623'
    type: object
    properties:
      messages:
        type: string
      value:
        type: string
    required:
    - messages
    - value
tags:
- name: Misc
  description: ''
