swagger: '2.0'
info:
  version: '1.0'
  title: View Approval Group details controller
  contact: {}
host: 132.145.228.83
basePath: /lending-origination/approval-group/AnRkr
securityDefinitions: {}
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /code/FGHV:
    get:
      summary: getApprovalGroupByCode
      tags:
      - Misc
      operationId: getApprovalGroupByCode
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters:
      - name: accept
        in: header
        required: true
        type: string
        description: ''
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/getApprovalGroupByCode'
          examples:
            application/json;charset=UTF-8:
              id: 1397401
              syncTs: 2023-03-04T10:18:45.172+0000
              version: 0
              tenantId: AnRkr
              code: FGHV
              name: Approval Group test
              description: null
              minimumApprovals: 6
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-03-04T10:18:45.172+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: APC1
              approvalCategoryDetailsId: 229217
          headers:
            Date:
              type: string
              default: Thu, 20 Jul 2023 14:25:00 GMT
            Content-Length:
              type: string
              default: '448'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"01cde255d9b6731ea8ef411c9a8a96856"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '14'
  /1397401:
    get:
      summary: getApprovalGroupById
      tags:
      - Misc
      operationId: getApprovalGroupById
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters:
      - name: accept
        in: header
        required: true
        type: string
        description: ''
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/getApprovalGroupById'
          examples:
            application/json;charset=UTF-8:
              id: 1397401
              syncTs: 2023-03-04T10:18:45.172+0000
              version: 0
              tenantId: AnRkr
              code: FGHV
              name: Approval Group test
              description: null
              minimumApprovals: 6
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-03-04T10:18:45.172+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList:
              - id: 1397402
                syncTs: 2023-03-04T10:18:45.362+0000
                version: 0
                tenantId: AnRkr
                code: DSCR
                value: value
                fromDate: null
                toDate: null
                fromAmount: null
                toAmount: null
                eqaulString: '12'
                status: ACTIVE
                createdUser: tharuki.ariyapala
                createdDate: 2023-03-04T10:18:45.362+0000
                modifiedUser: null
                modifiedDate: null
                approvalCategoryVariableId: 273710
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: APC1
              approvalCategoryDetailsId: 229217
          headers:
            Date:
              type: string
              default: Thu, 20 Jul 2023 14:24:06 GMT
            Content-Length:
              type: string
              default: '817'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0e0c8a3bf42c68038d0a7595d4a85d140"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '21'
  /all:
    get:
      summary: getAllApprovalGroup
      tags:
      - Misc
      operationId: getAllApprovalGroup
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            default: ''
            items:
              $ref: '#/definitions/getAllApprovalGroup'
          examples:
            application/json;charset=UTF-8:
            - id: 1330450
              syncTs: 2023-02-22T08:23:13.107+0000
              version: 0
              tenantId: AnRkr
              code: TRW1
              name: CATE 123
              description: test
              minimumApprovals: 6
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-02-22T08:23:13.107+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 298999
              approvalCategoryDetailsCode: QWEQ
            - id: 1397401
              syncTs: 2023-03-04T10:18:45.172+0000
              version: 0
              tenantId: AnRkr
              code: FGHV
              name: Approval Group test
              description: null
              minimumApprovals: 6
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-03-04T10:18:45.172+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 229217
              approvalCategoryDetailsCode: APC1
            - id: 1535743
              syncTs: 2023-03-14T08:28:14.863+0000
              version: 0
              tenantId: AnRkr
              code: DDDD
              name: Nish
              description: wdw
              minimumApprovals: 67
              status: ACTIVE
              createdUser: tttttttttttttttttttt
              createdDate: 2023-03-14T08:28:14.863+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 188975
              approvalCategoryDetailsCode: AC01
            - id: 1540567
              syncTs: 2023-03-16T08:36:39.381+0000
              version: 0
              tenantId: AnRkr
              code: HGHJ
              name: Name test
              description: null
              minimumApprovals: 2
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-03-16T08:36:39.381+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 1539928
              approvalCategoryDetailsCode: DFFD
            - id: 273716
              syncTs: 2022-08-24T17:12:36.531+0000
              version: 0
              tenantId: AnRkr
              code: TEST
              name: Managers
              description: null
              minimumApprovals: 5
              status: ACTIVE
              createdUser: sahan.peiris
              createdDate: 2022-08-24T17:12:36.531+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 229217
              approvalCategoryDetailsCode: APC1
            - id: 274175
              syncTs: 2023-02-08T16:02:25.365+0000
              version: 1
              tenantId: AnRkr
              code: ERFD
              name: sdfsdf
              description: sdfsdf
              minimumApprovals: 2
              status: ACTIVE
              createdUser: MilanCha
              createdDate: 2023-02-08T16:02:25.365+0000
              modifiedUser: MilanCha
              modifiedDate: 2023-02-08T16:02:25.365+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 184709
              approvalCategoryDetailsCode: BBBB
            - id: 1397469
              syncTs: 2023-03-04T11:23:46.732+0000
              version: 0
              tenantId: AnRkr
              code: ASRD
              name: Approva Tes
              description: null
              minimumApprovals: 3
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-03-04T11:23:46.732+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 1397465
              approvalCategoryDetailsCode: ASDR
            - id: 1535358
              syncTs: 2023-03-16T03:56:56.176+0000
              version: 1
              tenantId: AnRkr
              code: 4TRF
              name: Nish
              description: dff
              minimumApprovals: 67
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-03-16T03:56:56.176+0000
              modifiedUser: thiloshana.gamage
              modifiedDate: 2023-03-16T03:56:56.176+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 251629
              approvalCategoryDetailsCode: AA02
            - id: 1535844
              syncTs: 2023-03-14T08:41:09.250+0000
              version: 0
              tenantId: AnRkr
              code: UIYY
              name: Nish02
              description: ww
              minimumApprovals: 55
              status: ACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-03-14T08:41:09.250+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 251629
              approvalCategoryDetailsCode: AA02
            - id: 1539933
              syncTs: 2023-03-16T03:55:59.722+0000
              version: 0
              tenantId: AnRkr
              code: ASDR
              name: Name 01
              description: null
              minimumApprovals: 2
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-03-16T03:55:59.722+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 1539928
              approvalCategoryDetailsCode: DFFD
            - id: 1574104
              syncTs: 2023-03-26T15:15:48.523+0000
              version: 1
              tenantId: AnRkr
              code: '6666'
              name: n
              description: n
              minimumApprovals: 3
              status: INACTIVE
              createdUser: bhagyaa
              createdDate: 2023-03-26T15:15:48.523+0000
              modifiedUser: bhagyaa
              modifiedDate: 2023-03-26T15:15:48.523+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 298999
              approvalCategoryDetailsCode: QWEQ
            - id: 1535351
              syncTs: 2023-03-14T06:51:54.465+0000
              version: 0
              tenantId: AnRkr
              code: SDDD
              name: Nish
              description: null
              minimumApprovals: 34
              status: ACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-03-14T06:51:54.465+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 298999
              approvalCategoryDetailsCode: QWEQ
            - id: 1027895
              syncTs: 2023-02-09T10:15:03.190+0000
              version: 2
              tenantId: AnRkr
              code: TES4
              name: Managers -o
              description: null
              minimumApprovals: 6
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-02-09T10:15:03.190+0000
              modifiedUser: tharuki.ariyapala
              modifiedDate: 2023-02-09T10:15:03.190+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 251623
              approvalCategoryDetailsCode: AA01
            - id: 1535809
              syncTs: 2023-03-14T08:38:04.490+0000
              version: 0
              tenantId: AnRkr
              code: WERT
              name: Nish1
              description: ed
              minimumApprovals: 34
              status: ACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-03-14T08:38:04.490+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 188975
              approvalCategoryDetailsCode: AC01
            - id: 1540581
              syncTs: 2023-03-16T08:38:19.473+0000
              version: 0
              tenantId: AnRkr
              code: HYTT
              name: Name t1
              description: null
              minimumApprovals: 3
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-03-16T08:38:19.473+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 1539928
              approvalCategoryDetailsCode: DFFD
            - id: 1277479
              syncTs: 2023-01-31T05:55:21.866+0000
              version: 0
              tenantId: AnRkr
              code: AP1B
              name: approval g1
              description: null
              minimumApprovals: 2
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-01-31T05:55:21.866+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 229217
              approvalCategoryDetailsCode: APC1
            - id: 261379
              syncTs: 2023-07-04T03:06:45.170+0000
              version: 18
              tenantId: AnRkr
              code: MYGR
              name: Branch Manager
              description: group for test
              minimumApprovals: 1
              status: ACTIVE
              createdUser: acentura.testing
              createdDate: 2023-07-04T03:06:45.170+0000
              modifiedUser: acentura.testing
              modifiedDate: 2023-07-04T03:06:45.170+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 250276
              approvalCategoryDetailsCode: CACD
            - id: 261382
              syncTs: 2023-04-18T11:56:45.065+0000
              version: 3
              tenantId: AnRkr
              code: MNBV
              name: Regional Manager
              description: for test
              minimumApprovals: 1
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-04-18T11:56:45.065+0000
              modifiedUser: thiloshana.gamage
              modifiedDate: 2023-04-18T11:56:45.065+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 250276
              approvalCategoryDetailsCode: CACD
            - id: 1354363
              syncTs: 2023-02-24T06:06:46.234+0000
              version: 0
              tenantId: AnRkr
              code: ABHI
              name: Thiloshana Gamage
              description: null
              minimumApprovals: 2
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-02-24T06:06:46.234+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 250276
              approvalCategoryDetailsCode: CACD
            - id: 1396330
              syncTs: 2023-03-03T14:34:33.586+0000
              version: 2
              tenantId: AnRkr
              code: TESO
              name: Managers - T0
              description: null
              minimumApprovals: 5
              status: ACTIVE
              createdUser: MilanCha
              createdDate: 2023-03-03T14:34:33.586+0000
              modifiedUser: MilanCha
              modifiedDate: 2023-03-03T14:34:33.586+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 229217
              approvalCategoryDetailsCode: APC1
            - id: 1396954
              syncTs: 2023-03-03T20:32:03.133+0000
              version: 0
              tenantId: AnRkr
              code: TESP
              name: Managers -T1
              description: null
              minimumApprovals: 5
              status: ACTIVE
              createdUser: milan
              createdDate: 2023-03-03T20:32:03.131+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 229217
              approvalCategoryDetailsCode: APC1
            - id: 1396956
              syncTs: 2023-03-03T20:36:27.179+0000
              version: 0
              tenantId: AnRkr
              code: TESR
              name: Managers -T1
              description: null
              minimumApprovals: 5
              status: ACTIVE
              createdUser: milan
              createdDate: 2023-03-03T20:36:27.178+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 229217
              approvalCategoryDetailsCode: APC1
            - id: 1531371
              syncTs: 2023-03-10T09:28:46.083+0000
              version: 1
              tenantId: AnRkr
              code: ASER
              name: Approval 4
              description: test
              minimumApprovals: 2
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-03-10T09:28:46.083+0000
              modifiedUser: thiloshana.gamage
              modifiedDate: 2023-03-10T09:28:46.083+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 1397465
              approvalCategoryDetailsCode: ASDR
          headers:
            Date:
              type: string
              default: Thu, 20 Jul 2023 14:24:16 GMT
            Content-Length:
              type: string
              default: '10371'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"0a16a5298e3092258745ae598b5f9505d"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '21'
  /status/ACTIVE:
    get:
      summary: getApprovalGroupByStatus
      tags:
      - Misc
      operationId: getApprovalGroupByStatus
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            default: ''
            items:
              $ref: '#/definitions/getApprovalGroupByStatus'
          examples:
            application/json;charset=UTF-8:
            - id: 1330450
              syncTs: 2023-02-22T08:23:13.107+0000
              version: 0
              tenantId: AnRkr
              code: TRW1
              name: CATE 123
              description: test
              minimumApprovals: 6
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-02-22T08:23:13.107+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: QWEQ
              approvalCategoryDetailsId: 298999
            - id: 1397401
              syncTs: 2023-03-04T10:18:45.172+0000
              version: 0
              tenantId: AnRkr
              code: FGHV
              name: Approval Group test
              description: null
              minimumApprovals: 6
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-03-04T10:18:45.172+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: APC1
              approvalCategoryDetailsId: 229217
            - id: 1535743
              syncTs: 2023-03-14T08:28:14.863+0000
              version: 0
              tenantId: AnRkr
              code: DDDD
              name: Nish
              description: wdw
              minimumApprovals: 67
              status: ACTIVE
              createdUser: tttttttttttttttttttt
              createdDate: 2023-03-14T08:28:14.863+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: AC01
              approvalCategoryDetailsId: 188975
            - id: 1540567
              syncTs: 2023-03-16T08:36:39.381+0000
              version: 0
              tenantId: AnRkr
              code: HGHJ
              name: Name test
              description: null
              minimumApprovals: 2
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-03-16T08:36:39.381+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: DFFD
              approvalCategoryDetailsId: 1539928
            - id: 273716
              syncTs: 2022-08-24T17:12:36.531+0000
              version: 0
              tenantId: AnRkr
              code: TEST
              name: Managers
              description: null
              minimumApprovals: 5
              status: ACTIVE
              createdUser: sahan.peiris
              createdDate: 2022-08-24T17:12:36.531+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: APC1
              approvalCategoryDetailsId: 229217
            - id: 274175
              syncTs: 2023-02-08T16:02:25.365+0000
              version: 1
              tenantId: AnRkr
              code: ERFD
              name: sdfsdf
              description: sdfsdf
              minimumApprovals: 2
              status: ACTIVE
              createdUser: MilanCha
              createdDate: 2023-02-08T16:02:25.365+0000
              modifiedUser: MilanCha
              modifiedDate: 2023-02-08T16:02:25.365+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: BBBB
              approvalCategoryDetailsId: 184709
            - id: 1397469
              syncTs: 2023-03-04T11:23:46.732+0000
              version: 0
              tenantId: AnRkr
              code: ASRD
              name: Approva Tes
              description: null
              minimumApprovals: 3
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-03-04T11:23:46.732+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: ASDR
              approvalCategoryDetailsId: 1397465
            - id: 1535358
              syncTs: 2023-03-16T03:56:56.176+0000
              version: 1
              tenantId: AnRkr
              code: 4TRF
              name: Nish
              description: dff
              minimumApprovals: 67
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-03-16T03:56:56.176+0000
              modifiedUser: thiloshana.gamage
              modifiedDate: 2023-03-16T03:56:56.176+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: AA02
              approvalCategoryDetailsId: 251629
            - id: 1535844
              syncTs: 2023-03-14T08:41:09.250+0000
              version: 0
              tenantId: AnRkr
              code: UIYY
              name: Nish02
              description: ww
              minimumApprovals: 55
              status: ACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-03-14T08:41:09.250+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: AA02
              approvalCategoryDetailsId: 251629
            - id: 1539933
              syncTs: 2023-03-16T03:55:59.722+0000
              version: 0
              tenantId: AnRkr
              code: ASDR
              name: Name 01
              description: null
              minimumApprovals: 2
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-03-16T03:55:59.722+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: DFFD
              approvalCategoryDetailsId: 1539928
            - id: 1535351
              syncTs: 2023-03-14T06:51:54.465+0000
              version: 0
              tenantId: AnRkr
              code: SDDD
              name: Nish
              description: null
              minimumApprovals: 34
              status: ACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-03-14T06:51:54.465+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: QWEQ
              approvalCategoryDetailsId: 298999
            - id: 1027895
              syncTs: 2023-02-09T10:15:03.190+0000
              version: 2
              tenantId: AnRkr
              code: TES4
              name: Managers -o
              description: null
              minimumApprovals: 6
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-02-09T10:15:03.190+0000
              modifiedUser: tharuki.ariyapala
              modifiedDate: 2023-02-09T10:15:03.190+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: AA01
              approvalCategoryDetailsId: 251623
            - id: 1535809
              syncTs: 2023-03-14T08:38:04.490+0000
              version: 0
              tenantId: AnRkr
              code: WERT
              name: Nish1
              description: ed
              minimumApprovals: 34
              status: ACTIVE
              createdUser: sahan.peiris
              createdDate: 2023-03-14T08:38:04.490+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: AC01
              approvalCategoryDetailsId: 188975
            - id: 1540581
              syncTs: 2023-03-16T08:38:19.473+0000
              version: 0
              tenantId: AnRkr
              code: HYTT
              name: Name t1
              description: null
              minimumApprovals: 3
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-03-16T08:38:19.473+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: DFFD
              approvalCategoryDetailsId: 1539928
            - id: 1277479
              syncTs: 2023-01-31T05:55:21.866+0000
              version: 0
              tenantId: AnRkr
              code: AP1B
              name: approval g1
              description: null
              minimumApprovals: 2
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-01-31T05:55:21.866+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: APC1
              approvalCategoryDetailsId: 229217
            - id: 261379
              syncTs: 2023-07-04T03:06:45.170+0000
              version: 18
              tenantId: AnRkr
              code: MYGR
              name: Branch Manager
              description: group for test
              minimumApprovals: 1
              status: ACTIVE
              createdUser: acentura.testing
              createdDate: 2023-07-04T03:06:45.170+0000
              modifiedUser: acentura.testing
              modifiedDate: 2023-07-04T03:06:45.170+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: CACD
              approvalCategoryDetailsId: 250276
            - id: 261382
              syncTs: 2023-04-18T11:56:45.065+0000
              version: 3
              tenantId: AnRkr
              code: MNBV
              name: Regional Manager
              description: for test
              minimumApprovals: 1
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-04-18T11:56:45.065+0000
              modifiedUser: thiloshana.gamage
              modifiedDate: 2023-04-18T11:56:45.065+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: CACD
              approvalCategoryDetailsId: 250276
            - id: 1354363
              syncTs: 2023-02-24T06:06:46.234+0000
              version: 0
              tenantId: AnRkr
              code: ABHI
              name: Thiloshana Gamage
              description: null
              minimumApprovals: 2
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-02-24T06:06:46.234+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: CACD
              approvalCategoryDetailsId: 250276
            - id: 1396330
              syncTs: 2023-03-03T14:34:33.586+0000
              version: 2
              tenantId: AnRkr
              code: TESO
              name: Managers - T0
              description: null
              minimumApprovals: 5
              status: ACTIVE
              createdUser: MilanCha
              createdDate: 2023-03-03T14:34:33.586+0000
              modifiedUser: MilanCha
              modifiedDate: 2023-03-03T14:34:33.586+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: APC1
              approvalCategoryDetailsId: 229217
            - id: 1396954
              syncTs: 2023-03-03T20:32:03.133+0000
              version: 0
              tenantId: AnRkr
              code: TESP
              name: Managers -T1
              description: null
              minimumApprovals: 5
              status: ACTIVE
              createdUser: milan
              createdDate: 2023-03-03T20:32:03.131+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: APC1
              approvalCategoryDetailsId: 229217
            - id: 1396956
              syncTs: 2023-03-03T20:36:27.179+0000
              version: 0
              tenantId: AnRkr
              code: TESR
              name: Managers -T1
              description: null
              minimumApprovals: 5
              status: ACTIVE
              createdUser: milan
              createdDate: 2023-03-03T20:36:27.178+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: APC1
              approvalCategoryDetailsId: 229217
            - id: 1531371
              syncTs: 2023-03-10T09:28:46.083+0000
              version: 1
              tenantId: AnRkr
              code: ASER
              name: Approval 4
              description: test
              minimumApprovals: 2
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-03-10T09:28:46.083+0000
              modifiedUser: thiloshana.gamage
              modifiedDate: 2023-03-10T09:28:46.083+0000
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsCode: ASDR
              approvalCategoryDetailsId: 1397465
          headers:
            Date:
              type: string
              default: Thu, 20 Jul 2023 14:24:25 GMT
            Content-Length:
              type: string
              default: '9918'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"05c7a833c1a8583e96ae93ab5741b64e6"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '38'
  /name/test:
    get:
      summary: getApprovalGroupByName
      tags:
      - Misc
      operationId: getApprovalGroupByName
      deprecated: false
      produces:
      - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            default: ''
            items:
              $ref: '#/definitions/getApprovalGroupByName'
          examples:
            application/json;charset=UTF-8:
            - id: 1397401
              syncTs: 2023-03-04T10:18:45.172+0000
              version: 0
              tenantId: AnRkr
              code: FGHV
              name: Approval Group test
              description: null
              minimumApprovals: 6
              status: ACTIVE
              createdUser: tharuki.ariyapala
              createdDate: 2023-03-04T10:18:45.172+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 229217
              approvalCategoryDetailsCode: APC1
            - id: 1540567
              syncTs: 2023-03-16T08:36:39.381+0000
              version: 0
              tenantId: AnRkr
              code: HGHJ
              name: Name test
              description: null
              minimumApprovals: 2
              status: ACTIVE
              createdUser: thiloshana.gamage
              createdDate: 2023-03-16T08:36:39.381+0000
              modifiedUser: null
              modifiedDate: null
              approvalGroupVariableList: null
              approvalGroupPreConditionsList: null
              approvalCategoryDetailsId: 1539928
              approvalCategoryDetailsCode: DFFD
          headers:
            Date:
              type: string
              default: Thu, 20 Jul 2023 14:24:34 GMT
            Content-Length:
              type: string
              default: '890'
            Connection:
              type: string
              default: keep-alive
            etag:
              type: string
              default: '"00943f928c670b93bc2404d30042683db"'
            x-content-type-options:
              type: string
              default: nosniff
            x-xss-protection:
              type: string
              default: 1; mode=block
            cache-control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            pragma:
              type: string
              default: no-cache
            expires:
              type: string
              default: '0'
            x-frame-options:
              type: string
              default: DENY
            x-envoy-upstream-service-time:
              type: string
              default: '16'
definitions:
  getApprovalGroupByCode:
    title: getApprovalGroupByCode
    example:
      id: 1397401
      syncTs: 2023-03-04T10:18:45.172+0000
      version: 0
      tenantId: AnRkr
      code: FGHV
      name: Approval Group test
      description: null
      minimumApprovals: 6
      status: ACTIVE
      createdUser: tharuki.ariyapala
      createdDate: 2023-03-04T10:18:45.172+0000
      modifiedUser: null
      modifiedDate: null
      approvalGroupVariableList: null
      approvalGroupPreConditionsList: null
      approvalCategoryDetailsCode: APC1
      approvalCategoryDetailsId: 229217
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      minimumApprovals:
        type: integer
        format: int32
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
      approvalGroupVariableList:
        type: string
      approvalGroupPreConditionsList:
        type: string
      approvalCategoryDetailsCode:
        type: string
      approvalCategoryDetailsId:
        type: integer
        format: int32
    required:
    - id
    - syncTs
    - version
    - tenantId
    - code
    - name
    - description
    - minimumApprovals
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
    - approvalGroupVariableList
    - approvalGroupPreConditionsList
    - approvalCategoryDetailsCode
    - approvalCategoryDetailsId
  getApprovalGroupById:
    title: getApprovalGroupById
    example:
      id: 1397401
      syncTs: 2023-03-04T10:18:45.172+0000
      version: 0
      tenantId: AnRkr
      code: FGHV
      name: Approval Group test
      description: null
      minimumApprovals: 6
      status: ACTIVE
      createdUser: tharuki.ariyapala
      createdDate: 2023-03-04T10:18:45.172+0000
      modifiedUser: null
      modifiedDate: null
      approvalGroupVariableList:
      - id: 1397402
        syncTs: 2023-03-04T10:18:45.362+0000
        version: 0
        tenantId: AnRkr
        code: DSCR
        value: value
        fromDate: null
        toDate: null
        fromAmount: null
        toAmount: null
        eqaulString: '12'
        status: ACTIVE
        createdUser: tharuki.ariyapala
        createdDate: 2023-03-04T10:18:45.362+0000
        modifiedUser: null
        modifiedDate: null
        approvalCategoryVariableId: 273710
      approvalGroupPreConditionsList: null
      approvalCategoryDetailsCode: APC1
      approvalCategoryDetailsId: 229217
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      minimumApprovals:
        type: integer
        format: int32
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
      approvalGroupVariableList:
        type: array
        items:
          $ref: '#/definitions/ApprovalGroupVariableList'
      approvalGroupPreConditionsList:
        type: string
      approvalCategoryDetailsCode:
        type: string
      approvalCategoryDetailsId:
        type: integer
        format: int32
    required:
    - id
    - syncTs
    - version
    - tenantId
    - code
    - name
    - description
    - minimumApprovals
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
    - approvalGroupVariableList
    - approvalGroupPreConditionsList
    - approvalCategoryDetailsCode
    - approvalCategoryDetailsId
  ApprovalGroupVariableList:
    title: ApprovalGroupVariableList
    example:
      id: 1397402
      syncTs: 2023-03-04T10:18:45.362+0000
      version: 0
      tenantId: AnRkr
      code: DSCR
      value: value
      fromDate: null
      toDate: null
      fromAmount: null
      toAmount: null
      eqaulString: '12'
      status: ACTIVE
      createdUser: tharuki.ariyapala
      createdDate: 2023-03-04T10:18:45.362+0000
      modifiedUser: null
      modifiedDate: null
      approvalCategoryVariableId: 273710
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      code:
        type: string
      value:
        type: string
      fromDate:
        type: string
      toDate:
        type: string
      fromAmount:
        type: string
      toAmount:
        type: string
      eqaulString:
        type: string
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
      approvalCategoryVariableId:
        type: integer
        format: int32
    required:
    - id
    - syncTs
    - version
    - tenantId
    - code
    - value
    - fromDate
    - toDate
    - fromAmount
    - toAmount
    - eqaulString
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
    - approvalCategoryVariableId
  getAllApprovalGroup:
    title: getAllApprovalGroup
    example:
      id: 1330450
      syncTs: 2023-02-22T08:23:13.107+0000
      version: 0
      tenantId: AnRkr
      code: TRW1
      name: CATE 123
      description: test
      minimumApprovals: 6
      status: ACTIVE
      createdUser: thiloshana.gamage
      createdDate: 2023-02-22T08:23:13.107+0000
      modifiedUser: null
      modifiedDate: null
      approvalGroupVariableList: null
      approvalGroupPreConditionsList: null
      approvalCategoryDetailsId: 298999
      approvalCategoryDetailsCode: QWEQ
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      minimumApprovals:
        type: integer
        format: int32
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
      approvalGroupVariableList:
        type: string
      approvalGroupPreConditionsList:
        type: string
      approvalCategoryDetailsId:
        type: integer
        format: int32
      approvalCategoryDetailsCode:
        type: string
    required:
    - id
    - syncTs
    - version
    - tenantId
    - code
    - name
    - description
    - minimumApprovals
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
    - approvalGroupVariableList
    - approvalGroupPreConditionsList
    - approvalCategoryDetailsId
    - approvalCategoryDetailsCode
  getApprovalGroupByStatus:
    title: getApprovalGroupByStatus
    example:
      id: 1330450
      syncTs: 2023-02-22T08:23:13.107+0000
      version: 0
      tenantId: AnRkr
      code: TRW1
      name: CATE 123
      description: test
      minimumApprovals: 6
      status: ACTIVE
      createdUser: thiloshana.gamage
      createdDate: 2023-02-22T08:23:13.107+0000
      modifiedUser: null
      modifiedDate: null
      approvalGroupVariableList: null
      approvalGroupPreConditionsList: null
      approvalCategoryDetailsCode: QWEQ
      approvalCategoryDetailsId: 298999
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      minimumApprovals:
        type: integer
        format: int32
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
      approvalGroupVariableList:
        type: string
      approvalGroupPreConditionsList:
        type: string
      approvalCategoryDetailsCode:
        type: string
      approvalCategoryDetailsId:
        type: integer
        format: int32
    required:
    - id
    - syncTs
    - version
    - tenantId
    - code
    - name
    - description
    - minimumApprovals
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
    - approvalGroupVariableList
    - approvalGroupPreConditionsList
    - approvalCategoryDetailsCode
    - approvalCategoryDetailsId
  getApprovalGroupByName:
    title: getApprovalGroupByName
    example:
      id: 1397401
      syncTs: 2023-03-04T10:18:45.172+0000
      version: 0
      tenantId: AnRkr
      code: FGHV
      name: Approval Group test
      description: null
      minimumApprovals: 6
      status: ACTIVE
      createdUser: tharuki.ariyapala
      createdDate: 2023-03-04T10:18:45.172+0000
      modifiedUser: null
      modifiedDate: null
      approvalGroupVariableList: null
      approvalGroupPreConditionsList: null
      approvalCategoryDetailsId: 229217
      approvalCategoryDetailsCode: APC1
    type: object
    properties:
      id:
        type: integer
        format: int32
      syncTs:
        type: string
      version:
        type: integer
        format: int32
      tenantId:
        type: string
      code:
        type: string
      name:
        type: string
      description:
        type: string
      minimumApprovals:
        type: integer
        format: int32
      status:
        type: string
      createdUser:
        type: string
      createdDate:
        type: string
      modifiedUser:
        type: string
      modifiedDate:
        type: string
      approvalGroupVariableList:
        type: string
      approvalGroupPreConditionsList:
        type: string
      approvalCategoryDetailsId:
        type: integer
        format: int32
      approvalCategoryDetailsCode:
        type: string
    required:
    - id
    - syncTs
    - version
    - tenantId
    - code
    - name
    - description
    - minimumApprovals
    - status
    - createdUser
    - createdDate
    - modifiedUser
    - modifiedDate
    - approvalGroupVariableList
    - approvalGroupPreConditionsList
    - approvalCategoryDetailsId
    - approvalCategoryDetailsCode
tags:
- name: Misc
  description: ''
